### ISSUE TITLE
Save profile pics as image

### ISSUE THREAD

**Issue by MrHappy** [f41c0r/Python-Android-Facebook-Contact-Sync#3]
Is it possible to save the image as file?

**Comment by f41c0r** [comment]
Yes. From the scraper:
```python
rawPicFromInternet100100 = urllib.urlopen(link).read()
rawPicFromInternet100100Bytes = io.BytesIO(rawPicFromInternet100100)
```

If instead of resizing it and base64 encoding it you saved it to a file, you could download all of your contact photos.

**Comment by MrHappy** [comment]
thanks.. 
changed that and it works!

**Comment by f41c0r** [comment]
You would have to edit the script to follow the links to each individual contact's facebook profile, and then parse that to get the links to the contact photo embedded in their profile.
